#!/bin/sh

#
#  Upgrade servald if an upgrade is available.
#
# [ -e /dos/serval.up ] && /etc/serval/upgrade /dos/serval.up >>/dos/upgrade.log
# [ -e /dos/SERVAL.UP ] && /etc/serval/upgrade /dos/SERVAL.UP >>/dos/upgrade.log

#
# Clear out old pid file
#
rm /etc/serval/servald.pid

#
# run servald, and restart if it terminates for any reason
# (it is experimental software, after all).
#
while [ 1 ]
do
    # Copy our static config file to instance directory
    cp /etc/serval/serval.conf /serval-var/serval.conf

    # Run servald
    servald start foreground

    # Have a short delay before running again if it fails
    sleep 3
done
