#!/bin/sh

  if [ -e /dev/mmcblk0 ]; then
     # Bulk storage on SPI microSD
     dev=/dev/mmcblk0p
     fdiskdev=/dev/mmcblk0
  else
     if [ -e /dev/sda ]; then
        # Bulk storage on USB memory stick
        dev=/dev/sda
        fdiskdev=/dev/sda
     else
        # XXX - No bulk storage -- work out what to do.
        # We are now using microSD instead of USB, so our remedial options are different
         /etc/serval/boot_report WARN "No USB or microSD card.  Mesh Extender will not store or relay communications."
        exit
     fi
  fi


  # Check if /serval-var and /serval have been mounted read-write.
  # if not, or if they were never mounted at all, then create RAM disks
  # on those mount points
  svok=`mount | grep "/serval-var .*(rw" | wc -l`
  if [ $svok != 1 ]; then
    umount /serval-var
    fsck.ext4 -y /dev/sda3
    mount /dev/sda3 /serval-var
  fi
  sok=`mount | grep "/serval.*(rw" | wc -l`
  if [ $svok != 1 ]; then
    umount /serval
    fsck.ext4 -y /dev/sda2
    mount /dev/sda2 /serval
  fi
 
  # After mounting, check to make sure, in case the mounts above failed, in which case
  # we will use a ramfs
  /etc/serval/ramfs
