#!/bin/sh

  # Check if /serval-var and /serval have been mounted read-write.
  # if not, or if they were never mounted at all, then create RAM disks
  # on those mount points
  svok=`mount | grep "/serval-var .*(rw" | wc -l`
  if [ $svok != 1 ]; then
    umount /serval-var
    mount -t tmpfs -o nr_inodes=1k,mode=01777,nosuid,nodev,size=8M tmpfs /serval-var
  fi
  sok=`mount | grep "/serval.*(rw" | wc -l`
  if [ $svok != 1 ]; then
    umount /serval
    mount -t tmpfs -o nr_inodes=1k,mode=01777,nosuid,nodev,size=4M tmpfs /serval
    mkdir -p /serval/www
  fi

