#!/bin/csh -f

if ( -e testing ) then
  cd testing
endif

set count=1000

if ( "x$1" != "x" ) then
  set count=$1
endif

foreach n ( 1 2 3 4 )
 # Start relevant servald instance if required
 cd serval$n
 setenv SERVALINSTANCE_PATH `pwd`
 rm rhizome.db
 ../../serval-dna/servald start
 sleep 1
 ../../serval-dna/servald id self | tail -1 > self.sid

 # Repopulate rhizome with test bundles.
 ../../serval-dna/servald rhizome add file `cat self.sid` file$n

 foreach f ( $n{0,1,2,3,4,5,6,7,8,9}{0,1,2,3,4,5,6,7,8,9}{0,1,2,3,4,5,6,7,8,9} )
    set lines=`echo $f | cut -c1-3`
    hexdump /dev/random | head -20 | sed -e 's/[^f]//g'  > random$f
    hexdump /dev/random | head -$lines >> random$f
    ../../serval-dna/servald rhizome add file `cat self.sid` random$f
    rm random$f
    @ count = $count - 1
    if ( $count < 1 ) then
      break
    endif
 end 

  echo "foo" > from$n
  ../../serval-dna/servald rhizome add file `cat self.sid` from$n
  rm from$n

 cd ..
end 
