all:	auto-flash auto-flash-dragino

auto-flash:	auto-flash.c Makefile
	gcc -Wall -g -o auto-flash auto-flash.c

auto-flash-dragino: auto-flash-dragino.c Makefile
	gcc -Wall -g -o auto-flash-dragino auto-flash-dragino.c
