#!/bin/csh
foreach mn ( {0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F}{0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F} )
  echo -n `(echo NULL ; ( grep message_parser_$mn src/messages/*.c | cut -f2 -d" " | cut -f1 -d"(" ) ) | tail -1`
  echo ", // $mn"
end
