#!/bin/sh

# The following will result in the mesh extender having a different MAC and IP on every boot.
# While this may be inconvenient in some ways, it also ensures that over multiple reboots that no
# IP/MAC colissions should persist between nearby mesh extenders.  Drat that Birthday Paradox.

  ap0E=`dd if=/dev/urandom bs=5 count=1 | hexdump -e '1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X"'`
  ap1E=`dd if=/dev/urandom bs=5 count=1 | hexdump -e '1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X"'`
meshE=`dd if=/dev/urandom bs=5 count=1 | hexdump -e '1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X" ":" 1/1 "%02X"'`

#mesh ip is last 3 of mac munched to 10.0.0.0/8
  meship=`echo $meshE |awk -F: '{  p3=("0x" substr($3,0,2))+0; p4=("0x" substr($4,0,2))+0  ;\
         p5=("0x" substr($5,0,2))+0; printf "%d.%d.%d",p3,p4,p5 }' `

# AP IP is last 2 of mac munged to fit 172.16-31
  apip=`echo $ap0E |awk -F: '{ p4=("0x" substr($4,0,2))+0 ; p5=("0x" substr($5,0,2))+0  ;printf "%d.%d",(16+p4%16),p5 }' `
# Keep AP IP handy for later use
  echo $apip >/tmp/apip.txt

echo $meship $meshE $ap0E $ap1E $apip

NETWORK_TEMPLATE="/etc/config/network.template"
if [ -e "/serval-var/network.template" ]; then
    NETWORK_TEMPLATE="/serval-var/network.template"
fi
sed -e s/MESHIP/$meship/g -e s/APIP/$apip/g -e s/MESHETHER/$meshE/g  -e s/APETHER0/$ap0E/g -e s/APETHER1/$ap1E/g < $NETWORK_TEMPLATE > /etc/config/network

# If left hanging around can cause problems.
# (should be deleted when we fresh install, but this doesn't always seem to be the case)
if [ -e /etc/dnsmasq.conf ]; then
  rm /etc/dnsmasq.conf
fi

echo WiFi enabled with IP $apip > /dev/kmsg
