#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=47

start() {

  if [ -e /dev/mmcblk0 ]; then
     # Bulk storage on SPI microSD
     dev=/dev/mmcblk0p
     if [ ! -e /dev/mmcblk0p3 ]; then
       # microSD card is not partitioned, so prepare it
       fdisk /dev/mmcblk0 <<EOF
d
1
d
2
d
3
d
4
n
p
1

+250M
n
p
2

+1G
n
p
3


t
1
c
w
EOF
	mkfs.vfat /dev/mmcblk0p1
	mkfs.ext2 /dev/mmcblk0p2
	mkfs.ext2 /dev/mmcblk0p3
     fi
  else
     if [  -e /dev/sda1 ]; then
        # Bulk storage on USB
        dev=/dev/sda
     else
        # XXX - No bulk storage -- work out what to do.
        # We are now using microSD instead of USB, so our remedial options are different
        exit
     fi
  fi

  umount /dos
  umount /serval
  umount /serval-var

  fsck.ext2 -y ${dev}2
  fsck.ext2 -y ${dev}3
  dosfsck -y ${dev}1
  
  umount /dos
  mount ${dev}1 /dos
  if [ $? == 255 ]; then
    echo "Reformatting /dos"
    mkfs.vfat ${dev}1
    mount ${dev}1 /dos
  fi
  mount ${dev}2 /serval
  if [ $? == 255 ]; then
     echo "Reformatting /serval"
     mkfs.ext2 ${dev}2
    mount ${dev}2 /serval
  fi
  mount ${dev}3 /serval-var
  if [ $? == 255 ]; then
    echo "Reformatting /serval-var"
    mkfs.vfat ${dev}3
    mount ${dev}3 /serval-var
  fi

  dosmounted=`mount | grep /dos | wc -l`

  if [ -e ${dev}1 ] && [ "x$dosmounted" == "x0" ]; then
    # on first boot, the partitions are mounted under /tmp instead of in
    # the right place, so reboot
    sleep 60 # Give us time to log in remotely to fix anything broken
    reboot
  fi
  # If that wasn't the problem, and there is no device, or it hasn't mounted,
  # then we have a bigger problem ...
  if [ ! -e ${dev}1 ] || [ -e /serval/MeshExtender ] || [ -e /serval-var/MeshExtender ]; then
    # No storage present, or failed to mount -- this can be caused by a known hardware bug
    # in the Atheros 9k USB host controller. It can only be fixed by 
    # physically removing power -- a soft reset doesn't work.
    # To at least alert the user that this is happening, we will
    # blink the LEDs in a distinctive pattern.
    # XXX - We might be able to use the GPIO that cuts USB host power to fix this situation.
    echo "WARNING: Could not mount /serval or /serval-var"  
  fi 

  # Finally, read the EEPROM on the power cable, and set some parameters
  flash900 eeprom /dev/ttyATH0 directives list > /serval-var/eeprom.directives
  otabid=`flash900 eeprom /dev/ttyATH0 directives get OTABID | cut -f2 -d=`
  yesroot=`flash900 eeprom /dev/ttyATH0 directives get YESROOT | cut -f2 -d=`
  noroot=`flash900 eeprom /dev/ttyATH0 directives get NOROOT | cut -f2 -d=`
  if [ "x$otabid" != "x" ]; then
    echo $otabid >/dos/otabid.txt
  fi
  if [ "x$yesroot" != "x" ]; then
    echo $yesroot >/dos/yesroot
    rm /dos/noroot
  fi
  if [ "x$noroot" != "x" ]; then
    touch /dos/noroot
    rm /dos/yesroot
  fi
  
 
}

