#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=49

start() {
    /etc/serval/boot_report OK "Entering S49servald"

    # Clear out old inittab incase it tries to include ttyATH0
    # atleast that way a reboot will get things working.

    /etc/serval/boot_report OK "Reseting /etc/inittab to default"
    if [ -e /overlay/etc/inittab ]; then
	rm /overlay/etc/inittab
	reboot
    fi
    /etc/serval/boot_report OK "/etc/inittab ok"

    # Start servald
    /etc/serval/boot_report OK "Setting up SERVALINSTANCE_PATH"
    export SERVALINSTANCE_PATH=/serval-var
    mkdir -p $SERVALINSTANCE_PATH
    mkdir -p /var/run/serval
    mkdir -p $SERVALINSTANCE_PATH/log
    cp /etc/serval/serval.conf $SERVALINSTANCE_PATH/

    # Flash radio if required
    /etc/serval/boot_report OK "Checking if RFD900 requires re-flashing"
    flash900 /etc/serval/rfd900 /dev/ttyATH0 >/dos/flash900.log 2>&1 

    # Add identity to keyring file if none there yet
    lines=`servald keyring list | wc -l`
    if [ $lines == 2 ]; then
      servald keyring add
    fi

    # Add identity to keyrnig file if none there yet
    lines=`servald keyring list | wc -l`
    if [ $lines == 2 ]; then
        servald keyring Add
    fi

    /etc/serval/boot_report OK "Starting servald, lbard and otaupdate"
    /etc/serval/runservald &
    /etc/serval/runlbard &
    /etc/serval/otaupdate &

    /etc/serval/boot_report OK "Finished S49servald"
}

stop() {
  export SERVALINSTANCE_PATH=/serval-var
  servald stop
  pkill runlbard lbard
}
