#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

start() {

    /etc/serval/boot_report OK "Entering S99mountcheck"    

    # Check if things that we mounted in S47 are still mounted.
    # This is required because it seems that when the jffs finishes preparing
    # for the first time, the mountpoints are removed, requiring us to normally
    # need to reboot.
    # So we have two choices here:
    # 1. Reboot; or
    # 2. Mount the partitions again.
    mount > /tmp/mount99.log

    before=`cat /tmp/mount47.log | grep serval | wc -l`
    after=`cat /tmp/mount99.log | grep serval | wc -l`

    if [ "x$before" != "x$after" ]; then
       # For now, just notice the problem.  We'll implement action soon
       echo "$before $after" > /tmp/mount_problem
       /etc/serval/boot_report ERROR "/serval and /serval-var unmounted (probably by jffs2 mount) -- rebooting"    
       sleep 10
       reboot
    fi

    /etc/serval/boot_report OK "Exiting S99mountcheck"    

    # Put regular home page in place
    cp /tmp/www/index.html /tmp/www/bootlog.html
    cp /etc/serval/index_postboot.html /tmp/www/index.html
    cp /tmp/eeprom.data /tmp/www/eeprom_data.txt
    cp /serval-var/eeprom.dump /tmp/www/eeprom_dump.txt
}
