#!/bin/sh
keyValSSID="$(flash900 eeprom /dev/ttyUSB0 directives get SSID)"
SSID="${keyValSSID##*=}"

if [ $SSID ]; then
  sed -i 's|public.servalproject.org|'`echo $SSID`'|' /etc/config/wireless.template
#else
#  sed -i 's|public.servalproject.org|servalproject.org|' /etc/config/wireless.template
fi
