#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=17

start() {
	/etc/serval/boot_report OK "Entering S17mountstuff"    

     if [ -e /dev/sda ]; then
        # Bulk storage on USB memory stick	
        dev=/dev/sda
        fdiskdev=/dev/sda
	#notify boot report
	/etc/serval/boot_report WARN "Bulk storage (${fdiskdev}) found"  
     else
        # XXX - No bulk storage -- work out what to do.
       /etc/serval/boot_report WARN "No Bulk storage found"
     fi

  if [ ! -e ${dev}1 ]; then
	 # USB is not partitioned, so prepare it
	 /etc/serval/boot_report WARN "Bulk storage (${fdiskdev}) not partitioned -- running mkfs"   
	
       fdisk $fdiskdev <<EOF
d
1
n
p
1

t
1
c
t
4
82
w
EOF
	mkfs.vfat ${dev}1
  fi

fi
/etc/serval/boot_report OK "Mounting ${dev} to /mnt" 
mount ${dev}1 /mnt

  /etc/serval/boot_report OK "Exiting S17mountstuff"    

  
}

